import { engineInfo } from "../engine";
const nodes = [
  {id:'browser',x:25,y:250,w:140,name:'Organizer',note:'Browser workspace',color:'#eee5ff'},
  {id:'hosting',x:235,y:65,w:175,name:'AWS Amplify',note:'Web experience',icon:'Arch_AWS-Amplify_64'},
  {id:'auth',x:470,y:65,w:180,name:'Amazon Cognito',note:'Sign-in & access',color:'#eee5ff'},
  {id:'gateway',x:235,y:250,w:175,name:'API Gateway',note:'Authenticated requests',icon:'Arch_Amazon-API-Gateway_64'},
  {id:'planner',x:470,y:250,w:180,name:'AWS Lambda',note:'Planning & checks',icon:'Arch_AWS-Lambda_64'},
  {id:'logs',x:735,y:65,w:185,name:'CloudWatch',note:'Logs & alerts',icon:'Arch_Amazon-CloudWatch_64'},
  {id:'queue',x:735,y:250,w:185,name:'Amazon SQS',note:'Approved-plan queue',color:'#ffe6d0'},
  {id:'worker',x:735,y:430,w:185,name:'AWS Lambda',note:'Signed delivery',icon:'Arch_AWS-Lambda_64'},
  {id:'secret',x:470,y:430,w:180,name:'Secrets Manager',note:'Webhook signing key',color:'#e2f3d7'},
  {id:'failed',x:950,y:250,w:170,name:'SQS dead-letter',note:'Failed deliveries',color:'#ffe6d0'},
  {id:'recipient',x:735,y:645,w:185,name:'Connected service',note:'Your webhook recipient',color:'#fff1bf'},
  {id:'gemini',x:250,y:645,w:200,name:'Google Gemini',note:'Optional explanations',color:'#eee5ff'},
];
export function Architecture({variant='page'}:{variant?:'page'|'strip'}) {
  if(variant==='strip')return <p className="workspace-status"><span className="dot dot--aws"/>{engineInfo.label}<span>· Your decisions stay in your control</span></p>;
  return <section className="arch" id="architecture" aria-labelledby="arch-h"><div className="section-heading"><div><p className="kicker">Behind the experience</p><h2 id="arch-h">Big plans. Thoughtful connections.</h2></div><span className="engine">{engineInfo.label}</span></div><p className="lede">Secure sign-in for cloud planning. Checked schedules. Approved updates delivered to your connected tools.</p><figure className="architecture-canvas"><svg viewBox="0 0 1160 790" role="img" aria-labelledby="architecture-title architecture-desc"><title id="architecture-title">PlanB cloud architecture</title><desc id="architecture-desc">Amplify hosts the workspace. Cognito signs in organizers and API Gateway validates their access tokens. Lambda plans and checks schedules, queues approved schedules in SQS, and optionally requests Gemini explanations. A separate Lambda signs webhook deliveries using Secrets Manager. Failed deliveries go to a dead-letter queue. CloudWatch records logs and alarms.</desc><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8" fill="#7b8697"/></marker></defs><rect x="200" y="20" width="940" height="585" rx="12" fill="#fffdf8" stroke="#a6b0be" strokeDasharray="6 4"/><text x="220" y="45" className="diagram-boundary">AWS CLOUD</text><g fill="none" stroke="#7b8697" strokeWidth="1.6" markerEnd="url(#arrow)"><path d="M95 250 V115 H235"/><path d="M165 300 H235"/><path d="M410 115 H470"/><path d="M560 165 V205 H322 V250" strokeDasharray="5 4"/><path d="M410 300 H470"/><path d="M650 300 H735"/><path d="M560 250 V195 H827 V165" strokeDasharray="5 4"/><path d="M827 350 V430"/><path d="M920 300 H950" strokeDasharray="5 4"/><path d="M650 480 H735" strokeDasharray="5 4"/><path d="M827 530 V645"/><path d="M470 335 H430 V610 H350 V645" strokeDasharray="5 4"/></g><g className="diagram-label"><text x="440" y="100">Sign in</text><text x="350" y="198">Token verification</text><text x="666" y="285">Approved</text><text x="840" y="398">Deliver</text><text x="837" y="624">HTTPS · signed</text><text x="293" y="626">Optional assistance</text></g>{nodes.map(n=><g key={n.id}><rect x={n.x} y={n.y} width={n.w} height="100" rx="10" fill={n.color??'#fff'} stroke="#a9a1b4"/>{n.icon && <image href={`/aws-icons/${n.icon}.svg`} x={n.x+n.w/2-18} y={n.y+8} width="36" height="36"/>}<text x={n.x+n.w/2} y={n.y+64} textAnchor="middle" className="diagram-name">{n.name}</text><text x={n.x+n.w/2} y={n.y+84} textAnchor="middle" className="diagram-note">{n.note}</text></g>)}</svg><figcaption>{engineInfo.remote ? 'Cloud services are configured. Sign in to use them.' : 'Cloud deployment design. This workspace currently runs planning in your browser; webhook delivery becomes available after cloud setup.'}</figcaption></figure></section>;
}
